Merged PR 61985: Use devcontainer ACR image
Porting over scripts from wabakimi so that the devcontainer can reference an image instead of a Dockerfile.

Also:
- Doing a `conda clean` after building the environment to reduce the image size
- Using `mamba` to create the environment. This is nearly 2x faster.
- Adding a script to download .net symbols when needed instead of adding them to the devcontainer image.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -22,6 +22,28 @@ jobs:
     KUBECONFIG: /etc/rancher/k3s/k3s.yaml
     GOBIN: '$(Agent.TempDirectory)/go/bin'
   steps:
+
+  - script: |
+      set -euo pipefail
+      image=$(.devcontainer/get-devcontainer-image.sh)
+      echo "##vso[task.setvariable variable=DEVCONTAINER_IMAGE]${image}"
+    displayName: Read devcontainer.json
+
+  - script: |
+      set -euo pipefail
+      docker pull ${DEVCONTAINER_IMAGE}
+    displayName: Pull devcontainer image
+
+  - script: |
+      set -euo pipefail
+      docker build -f .devcontainer/Dockerfile --target devcontainer -t devcontainer --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${DEVCONTAINER_IMAGE} .
+
+      if ! .devcontainer/diff-container-images.sh "${DEVCONTAINER_IMAGE}" devcontainer; then
+        echo 'Error: the "image" field in devcontainer.json does not reflect the current "devcontainer" target of the Dockerfile. Run .devcontainer/update-devcontainer-image.sh to correct this.'
+        exit 1
+      fi
+    displayName: Verify devcontainer.json
+
   - task: GoTool@0
     inputs:
       version: '1.17.3'
