Private networking (#251)

diff --git a/.github/workflows/pr-ci.yml b/.github/workflows/pr-ci.yml
--- a/.github/workflows/pr-ci.yml
+++ b/.github/workflows/pr-ci.yml
@@ -19,7 +19,7 @@ env:
 
   CAN_ACCESS_SECRETS: ${{ secrets.CAN_ACCESS_SECRETS }}
 
-  TYGER_TYGER_AUTH_METHOD: "github"
+  TYGER_AUTH_METHOD: "github"
 
 jobs:
   # If this is running a Dependabot PR or PR from a fork, it we won't have access to secrets
@@ -417,6 +417,118 @@ jobs:
         run: |
           set -euo pipefail
           make -s ${{ matrix.command }}
+
+  test-private-link-deployment:
+    needs:
+      - get-config
+    runs-on: ["self-hosted", "1ES.Pool=tyger-gh-1es-westus2"]
+    defaults:
+      run:
+        shell: bash
+    outputs:
+      TYGER_PRIVATE_LINK_URL: ${{ steps.capture-urls.outputs.TYGER_PRIVATE_LINK_URL }}
+      TYGER_PRIVATE_LINK_BUFFER_URL: ${{ steps.capture-urls.outputs.TYGER_PRIVATE_LINK_BUFFER_URL }}
+    env:
+      DO_NOT_BUILD_IMAGES: "true"
+      EXPLICIT_IMAGE_TAG: ${{ needs.get-config.outputs.IMAGE_TAG }}-amd64
+      TYGER_USE_PRIVATE_LINK: true
+      TYGER_ENVIRONMENT_NAME: ${{ needs.get-config.outputs.TYGER_ENVIRONMENT_NAME }}priv
+
+    steps:
+
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Log in to Azure
+        uses: ./.github/actions/login-azure
+
+      - name: Log in to ACR
+        run: |
+          make login-acr
+
+      - uses: actions/setup-go@v4
+        with:
+          go-version-file: cli/go.mod
+          cache-dependency-path: cli/go.sum
+
+      - name: up
+        run: |
+          set -euo pipefail
+          make -s up INSTALL_CLOUD=true
+          make -s migrate
+
+      - name: Run basic test
+        run: |
+          set -euo pipefail
+          make -s login
+          make -s basic-test-no-up
+
+      - name: Capture URLs
+        id: capture-urls
+        run: |
+          set -euo pipefail
+
+          tyger_url=$(make -s get-tyger-url)
+          echo "TYGER_PRIVATE_LINK_URL=$tyger_url" >> "$GITHUB_OUTPUT"
+
+          buffer_id=$(tyger buffer create)
+          echo "hello" | tyger buffer write "$buffer_id"
+          buffer_url=$(tyger buffer access $buffer_id)
+          echo "TYGER_PRIVATE_LINK_BUFFER_URL=$buffer_url" >> "$GITHUB_OUTPUT"
+
+  ensure-private-link-endpoints-not-public:
+    needs:
+      - test-private-link-deployment
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - uses: actions/setup-go@v4
+        with:
+          go-version-file: cli/go.mod
+          cache-dependency-path: cli/go.sum
+
+      - name: Build cli
+        run: |
+          set -euo pipefail
+          make -s install-cli
+
+      - name: Test endpoints fail from outside the private network
+        run: |
+          set -euo pipefail
+
+          tyger_url="${{ needs.test-private-link-deployment.outputs.TYGER_PRIVATE_LINK_URL }}"
+          if [[ -z "$tyger_url" ]]; then
+            echo "ERROR: TYGER_PRIVATE_LINK_URL is not set. Ensure the test-private-link-deployment job ran successfully."
+            exit 1
+          fi
+
+          buffer_url="${{ needs.test-private-link-deployment.outputs.TYGER_PRIVATE_LINK_BUFFER_URL }}"
+          if [[ -z "$buffer_url" ]]; then
+            echo "ERROR: TYGER_PRIVATE_LINK_BUFFER_URL is not set. Ensure the test-private-link-deployment job ran successfully."
+            exit 1
+          fi
+
+          # Test Tyger URL - should fail (not be accessible)
+          if curl -sSf "$tyger_url/metadata"; then
+            echo "ERROR: Private endpoint $tyger_url/metadata is accessible from outside the private network. This should not be possible."
+            exit 1
+          fi
+
+          # Test buffer URL
+          if tyger buffer read "$buffer_url"; then
+            echo "ERROR: Private endpoint $buffer_url is accessible from outside the private network. This should not be possible."
+            exit 1
+          fi
 
   windows-smoke-tests:
     needs:
